import Foundation

public struct MediaAttachment: Hashable, Codable, MediaIdentifiable, Sendable {
    public let id: MediaAttachmentID
    /// ID generated by the client for optimistic rendering
    public let clientID: MediaAttachmentID?
    public let uploadStarted: Date
    public let attachment: AttachmentType
    public var mediaIdentitifer: String {
        attachment.mediaIdentitifer
    }

    public enum AttachmentType: Hashable, Codable, MediaIdentifiable, Sendable {
        case giphy(GiphyAttachment)
        case photo(PhotoAttachment)
        
        enum Kind: String, Codable {
            case giphy
            case photo
        }
        
        public var mediaIdentitifer: String {
            switch self {
            case .giphy(let giphyAttachment):
                giphyAttachment.mediaIdentitifer
                
            case .photo(let photoAttachment):
                photoAttachment.mediaIdentitifer
            }
        }
        
        enum CodingKeys: String, CodingKey {
            case type
            case giphy
            case photo
        }
        
        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(Kind.self, forKey: .type)
            
            switch type {
            case .giphy:
                let giphy = try container.decode(GiphyAttachment.self, forKey: .giphy)
                self = .giphy(giphy)
                
            case .photo:
                let photo = try container.decode(PhotoAttachment.self, forKey: .photo)
                self = .photo(photo)
            }
        }
        
        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case .giphy(let giphyAttachment):
                try container.encode(Kind.giphy, forKey: .type)
                try container.encode(giphyAttachment, forKey: .giphy)
                
            case .photo(let photoAttachment):
                try container.encode(Kind.photo , forKey: .type)
                try container.encode(photoAttachment, forKey: .photo)
            }
        }
    }
    
    public init(
        id: MediaAttachmentID,
        clientID: MediaAttachmentID?,
        uploadStarted: Date,
        attachment: AttachmentType
    ) {
        self.id = id
        self.clientID = clientID
        self.uploadStarted = uploadStarted
        self.attachment = attachment
    }
    
    public enum CodingKeys: String, CodingKey {
        case id
        case clientID = "clientId"
        case uploadStarted = "uploadStarted"
        case attachment
    }
    
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(MediaAttachmentID.self, forKey: .id)
        self.clientID = try container.decodeIfPresent(MediaAttachmentID.self, forKey: .clientID)
        self.uploadStarted = try container.decode(Date.self, forKey: .uploadStarted)
        self.attachment = try container.decode(MediaAttachment.AttachmentType.self, forKey: .attachment)
    }
}
