import Foundation
import MediaModel
import UserModel

public struct ChatMessage: Equatable, Codable, Sendable {
    public let id: ChatMessageID
    /// ID generated by the client for optimistic rendering
    public let clientID: ChatMessageID?
    public let roomID: ChatRoomID
    public let userID: UserID
    public let displayName: String
    public let profileImageURL: URL?
    public let message: String
    public let timestamp: Date
    public let isDeleted: Bool
    public let attachments: [MediaAttachment]?
    public let reactionCounts: [String: Int]
    public let myReactions: Set<String>
    
    public enum CodingKeys: String, CodingKey {
        case id
        case clientID = "clientId"
        case roomID = "room"
        case userID = "user"
        case displayName = "username"
        case profileImageURL = "imageUrl"
        case message = "text"
        case timestamp = "created"
        case isDeleted
        case attachments
        case reactionCounts
        case myReactions
    }
    
    public init(
        id: ChatMessageID,
        clientID: ChatMessageID?,
        roomID: ChatRoomID,
        userID: UserID,
        displayName: String,
        profileImageURL: URL?,
        message: String,
        timestamp: Date,
        isDeleted: Bool,
        attachments: [MediaAttachment],
        reactionCounts: [String: Int] = [:],
        myReactions: Set<String> = []
    ) {
        self.id = id
        self.clientID = clientID
        self.roomID = roomID
        self.userID = userID
        self.displayName = displayName
        self.profileImageURL = profileImageURL
        self.message = message
        self.timestamp = timestamp
        self.isDeleted = isDeleted
        self.attachments = attachments
        self.reactionCounts = reactionCounts
        self.myReactions = myReactions
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(ChatMessageID.self, forKey: .id)
        clientID = try container.decodeIfPresent(ChatMessageID.self, forKey: .clientID)
        roomID = try container.decode(ChatRoomID.self, forKey: .roomID)
        userID = try container.decode(UserID.self, forKey: .userID)
        displayName = try container.decode(String.self, forKey: .displayName)
        profileImageURL = try container.decodeIfPresent(URL.self, forKey: .profileImageURL)
        message = try container.decode(String.self, forKey: .message)
        timestamp = try container.decode(Date.self, forKey: .timestamp)
        isDeleted = try container.decode(Bool.self, forKey: .isDeleted)
        attachments = try container.decodeIfPresent([MediaAttachment].self, forKey: .attachments)
        reactionCounts = try container.decodeIfPresent([String: Int].self, forKey: .reactionCounts) ?? [:]
        let reactionsArray = try container.decodeIfPresent([String].self, forKey: .myReactions) ?? []
        myReactions = Set(reactionsArray)
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(clientID, forKey: .clientID)
        try container.encode(roomID, forKey: .roomID)
        try container.encode(userID, forKey: .userID)
        try container.encode(displayName, forKey: .displayName)
        try container.encodeIfPresent(profileImageURL, forKey: .profileImageURL)
        try container.encode(message, forKey: .message)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(reactionCounts, forKey: .reactionCounts)
        try container.encode(Array(myReactions), forKey: .myReactions)
    }
}
